version: 'latest'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050    
    ports:
      - "5050:5050"
    depends_on:
      - postgres

  http_container:
    build: ../http
    container_name: http_container
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  vue_app:
    build: ../vue
    container_name: vue_container
    restart: always
    ports:
      - "5000:5000"  # Alterando para 5000
    depends_on:
      - http_container


volumes:
  postgres_data:
